spring:
  redis:
    host: ${zlt.redis.host}
    port: ${zlt.redis.port}
    timeout: ${zlt.redis.timeout}

zlt:
  oauth2:
    token:
      store:
        type: resJwt
  security:
    ignore:
      # 忽略认证的地址
      httpUrls: >
        /api-uaa/**,
        /api-user/users-anon/**,
        /login.html,
        /user/login
      # 配置只认证登录，登录后所有角色都能访问的url
      menusPaths: /api-user/menus/current
    auth:
      # 配置必需认证的url
      httpUrls: /api-uaa/clients/**
      #是否开启url级别权限
      urlEnabled: false

zuul:
  ribbon-isolation-strategy: thread
  ribbon:
    eager-load:
      enabled: true
    threadPool:
      useSeparateThreadPools: true
      threadPoolKeyPrefix: api-gateway
  #关闭重试
  retryable: false
  #/oauth/token需要请求头处理
  sensitive-headers:
  ignored-headers: Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Access-Control-Allow-Methods
  add-host-header: true
  routes:
    auth:
      path: /api-uaa/**
      service-id: uaa-server
      strip-prefix: true
      custom-sensitive-headers: true
    auth-login-page:
      path: /login.html
      service-id: uaa-server
      strip-prefix: true
      custom-sensitive-headers: true
    auth-login-process:
      path: /user/login
      service-id: uaa-server
      strip-prefix: true
      custom-sensitive-headers: true
    auth-login-token:
      path: /oauth/token
      service-id: uaa-server
      strip-prefix: true
      custom-sensitive-headers: true
    auth-login-authorize:
      path: /oauth/authorize
      service-id: uaa-server
      strip-prefix: true
      custom-sensitive-headers: true
    auth-check-process:
      path: /oauth/check_token
      service-id: uaa-server
      strip-prefix: true
      custom-sensitive-headers: true
    user:
      path: /api-user/**
      service-id: user-center
      strip-prefix: true
      custom-sensitive-headers: true
    file:
      path: /api-file/**
      service-id: file-center
      strip-prefix: true
    log:
      path: /api-log/**
      service-id: log-center
      strip-prefix: true
    generator:
      path: /api-generator/**
      service-id: code-generator
      strip-prefix: true
  ssl-hostname-validation-enabled: false

swagger:
  butler:
    api-docs-path:  v2/api-docs
    swagger-version: 2.0
    auto-generate-from-zuul-routes: true
    generate-routes: user,file